export const Routes = {
  home: "/",
  projects: "/dashboard/",
  issues: "/dashboard/issues",
  alerts: "/dashboard/alerts",
  users: "/dashboard/users",
  settings: "/dashboard/settings",
  docs: "#",
  api: "#",
  help: "#",
  community: "#",
  products: "/products",
  documentation: "/documentation",
  pricing: "/pricing",
};
